### PR TITLE
Fixed screenshot & updated GitHub URL to Material Theme for VSC

### PR DESCRIPTION
**Pull request by gitatmax**
Love your theme & thought the repo could use some love :)

### CODE REVIEW

**Comment by gitatmax** [comment]
@r3volution11

**Comment by r3volution11** [comment]
@gitatmax Heya, this is great, sorry I missed it. Thanks!

**Comment by gitatmax** [comment]
> @gitatmax Heya, this is great, sorry I missed it. Thanks!

Hey, of course! No worries, thanks for merging :)

**Comment by r3volution11** [comment]
@gitatmax Since Big Sur I've used a modified version and was thinking of providing it as an alternate. What do you think?

https://r3v.in/O9AW/Material-Palenight-Big-Sur.alfredappearance

**Comment by gitatmax** [comment]
@r3volution11 Thanks for asking. I am setting up a new machine and don't have Alfred set up yet to test. I don't think it hurts to have alternative styles for folks that want some variation, though! I'll check this out as soon as I can :)

**Pull request merged**
